spring:
#  datasource:
#    url: jdbc:h2:mem:airqdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=true
#    username: root
#    password: airq
#    continue-on-error: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  cloud:
    discovery:
      enabled: false
